Repository Kbank-Fe/wedding, pull requests merged in 2025-08, with the labels that each got.

#34 Feature/29-create-Userinfo-component
  src/components/Intro/UserInfo.tsx
  src/components/Intro/WeddingIntro.tsx
  src/types/TextAlignment.ts
  src/types/weddingIntro.ts
Labels: :sparkles:Feature

#32 Feature/24 create gallery components
  index.html
  package.json
  public/images/image1.png
  public/images/image10.png
  public/images/image2.png
  public/images/image3.png
  public/images/image4.png
  public/images/image5.png
  public/images/image6.png
  public/images/image7.png
  public/images/image8.png
  public/images/image9.png
  src/App.tsx
  src/components/gallery/Gallery.tsx
  src/components/gallery/GalleryView.tsx
  src/hooks/useViewportListener.ts
  src/pages/index.tsx
  src/stores/useThemeStore.ts
  src/stores/useViewportStore.ts
  src/styles/GlobalStyle.tsx
  src/types/react-image-gallery.d.ts
  yarn.lock
Labels: :sparkles:Feature, 💅Style

#35 Feature/27 create map component
  .gitignore
  package.json
  public/images/icon/kakao_map.png
  public/images/icon/naver_map.png
  public/images/icon/tmap.png
  src/components/account/AccordionItem.tsx
  src/components/map/MapBadge.tsx
  src/components/map/WeddingMap.tsx
  src/pages/index.tsx
  src/utils/constants/images.ts
  src/utils/constants/urls.ts
  yarn.lock
Labels: :sparkles:Feature

#39 Bugfix: DateCalendar 미사용 파라미터 제거
  package.json
  src/components/calendar/DateCalendar.tsx
  yarn.lock
Labels: :lady_beetle:BugFix

#45 Feature/36 create admin page and base component
  src/components/account/AccordionItem.tsx
  src/components/account/Account.tsx
  src/components/account/AccountList.tsx
  src/components/transport/TransportAdmin.tsx
  src/components/transport/TransportItem.tsx
  src/components/transport/TransportList.tsx
  src/pages/admin.tsx
  src/pages/index.tsx
  src/utils/adminList.ts
Labels: :sparkles:Feature, 💅Style

#60 Feature/44 create kakao login
  .gitignore
  api/auth/kakao/exchange.ts
  package-lock.json
  package.json
  public/images/kakao_login.png
  src/components/login/KakaoLoginButton.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/utils/firebase.ts
  src/utils/kakaoPopup.ts
  src/utils/shares.ts
  yarn.lock
Labels: :key:API, :sparkles:Feature
